kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: roboshop-efs
provisioner: efs.csi.aws.com
reclaimPolicy: Delete
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-00fd9e1b54f460ed6
  directoryPerms: "700"
  basePath: "/roboshop" 
  
  