apiVersion: v1
kind: service
metadata:
  name: nginx
spec:
  selector:
    # labels are used as delectors
    project: roboshop
    component: frontend
    envinorment: dev
  ports:
  - protocol: TCP
    port: 80 #sevice port (internal cluster IP)
    targetport: 80   # container port (must match your Pod's containerPort)