apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    project: roboshop
    purpose: rs-demo
    tier: frontend
    component: frontend
  annotations: 
    kubernetes.io/change-cause: "movind to 1.29"  
spec:
    replicas: 10
    selector:
      matchLabels:  
        project: roboshop
        purpose: rs-demo
        tier: frontend
        component: frontend
    template:
      metadata:
       labels:
        project: roboshop
        purpose: rs-demo
        tier: frontend
        component: frontend 
      spec:
        containers:
        - name: nginx
          image: nginx:1.29