apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    project: roboshop
    purpose: rs-demo
    tier: frontend
    component: frontend
  annotations: 
    kubernetes.io/change-cause: "movind to 1.29.7"  
spec:
    replicas: 4
    selector:
      matchLabels:  
        project: roboshop
        purpose: rs-demo
        tier: frontend
        component: frontend
    template:
      metadata:
       labels:
        project: roboshop
        purpose: rs-demo
        tier: frontend
        component: frontend 
      spec:
        containers:
        - name: nginx
          image: nginx:1.29.7
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    # labels are used as delectors
    project: roboshop
    component: frontend 
  ports:
  - protocol: TCP
    port: 80 #sevice port (internal cluster IP)
    targetPort: 80      
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-headless
spec:
  clusterIP: none
  selector:
    # labels are used as delectors
    project: roboshop
    component: frontend 
  ports:
  - protocol: TCP
    port: 80 #sevice port (internal cluster IP)
    targetPort: 80            